; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html


[env:STM32C011F6P6_Multi]
platform = ststm32
board = genericSTM32C011F6
framework = arduino
lib_deps =
;    mrrwa/NmraDcc @ ^2.0.16
    https://github.com/Rosscoetrain/NmraDcc

build_flags = 
    -D STM32C031xx
    -D PIO_FRAMEWORK_ARDUINO_SERIAL_DISABLED
    -D NO_HWSERIAL
;    -D HAL_UART_MODULE_ONLY
;    -D HAL_UART_MODULE_ENABLED
    -Wl,--no-warn-rwx-segments


upload_protocol = custom

upload_command =
    /home/ross/bin/openocd-st -f firmware_stm32c011f6p6.cfg


